// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: frontend-backend_master.proto

#include "frontend-backend_master.pb.h"
#include "frontend-backend_master.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace penncloud {
namespace frontend {

static const char* FrontendMasterService_method_names[] = {
  "/penncloud.frontend.FrontendMasterService/RegisterFrontend",
  "/penncloud.frontend.FrontendMasterService/ReceiveNodeUpdate",
};

std::unique_ptr< FrontendMasterService::Stub> FrontendMasterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FrontendMasterService::Stub> stub(new FrontendMasterService::Stub(channel, options));
  return stub;
}

FrontendMasterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterFrontend_(FrontendMasterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReceiveNodeUpdate_(FrontendMasterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FrontendMasterService::Stub::RegisterFrontend(::grpc::ClientContext* context, const ::penncloud::frontend::Empty& request, ::penncloud::frontend::Acknowledgment* response) {
  return ::grpc::internal::BlockingUnaryCall< ::penncloud::frontend::Empty, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterFrontend_, context, request, response);
}

void FrontendMasterService::Stub::async::RegisterFrontend(::grpc::ClientContext* context, const ::penncloud::frontend::Empty* request, ::penncloud::frontend::Acknowledgment* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::penncloud::frontend::Empty, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterFrontend_, context, request, response, std::move(f));
}

void FrontendMasterService::Stub::async::RegisterFrontend(::grpc::ClientContext* context, const ::penncloud::frontend::Empty* request, ::penncloud::frontend::Acknowledgment* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterFrontend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::penncloud::frontend::Acknowledgment>* FrontendMasterService::Stub::PrepareAsyncRegisterFrontendRaw(::grpc::ClientContext* context, const ::penncloud::frontend::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::penncloud::frontend::Acknowledgment, ::penncloud::frontend::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterFrontend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::penncloud::frontend::Acknowledgment>* FrontendMasterService::Stub::AsyncRegisterFrontendRaw(::grpc::ClientContext* context, const ::penncloud::frontend::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterFrontendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendMasterService::Stub::ReceiveNodeUpdate(::grpc::ClientContext* context, const ::penncloud::frontend::NodeUpdate& request, ::penncloud::frontend::Acknowledgment* response) {
  return ::grpc::internal::BlockingUnaryCall< ::penncloud::frontend::NodeUpdate, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReceiveNodeUpdate_, context, request, response);
}

void FrontendMasterService::Stub::async::ReceiveNodeUpdate(::grpc::ClientContext* context, const ::penncloud::frontend::NodeUpdate* request, ::penncloud::frontend::Acknowledgment* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::penncloud::frontend::NodeUpdate, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReceiveNodeUpdate_, context, request, response, std::move(f));
}

void FrontendMasterService::Stub::async::ReceiveNodeUpdate(::grpc::ClientContext* context, const ::penncloud::frontend::NodeUpdate* request, ::penncloud::frontend::Acknowledgment* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReceiveNodeUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::penncloud::frontend::Acknowledgment>* FrontendMasterService::Stub::PrepareAsyncReceiveNodeUpdateRaw(::grpc::ClientContext* context, const ::penncloud::frontend::NodeUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::penncloud::frontend::Acknowledgment, ::penncloud::frontend::NodeUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReceiveNodeUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::penncloud::frontend::Acknowledgment>* FrontendMasterService::Stub::AsyncReceiveNodeUpdateRaw(::grpc::ClientContext* context, const ::penncloud::frontend::NodeUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReceiveNodeUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

FrontendMasterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendMasterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendMasterService::Service, ::penncloud::frontend::Empty, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::penncloud::frontend::Empty* req,
             ::penncloud::frontend::Acknowledgment* resp) {
               return service->RegisterFrontend(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendMasterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendMasterService::Service, ::penncloud::frontend::NodeUpdate, ::penncloud::frontend::Acknowledgment, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendMasterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::penncloud::frontend::NodeUpdate* req,
             ::penncloud::frontend::Acknowledgment* resp) {
               return service->ReceiveNodeUpdate(ctx, req, resp);
             }, this)));
}

FrontendMasterService::Service::~Service() {
}

::grpc::Status FrontendMasterService::Service::RegisterFrontend(::grpc::ServerContext* context, const ::penncloud::frontend::Empty* request, ::penncloud::frontend::Acknowledgment* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendMasterService::Service::ReceiveNodeUpdate(::grpc::ServerContext* context, const ::penncloud::frontend::NodeUpdate* request, ::penncloud::frontend::Acknowledgment* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace penncloud
}  // namespace frontend

