// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: backend_master_kv.proto
#ifndef GRPC_backend_5fmaster_5fkv_2eproto__INCLUDED
#define GRPC_backend_5fmaster_5fkv_2eproto__INCLUDED

#include "backend_master_kv.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace penncloud {
namespace backend {

// Service for managing backend nodes
class BackendMasterKVService final {
 public:
  static constexpr char const* service_full_name() {
    return "penncloud.backend.BackendMasterKVService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Health check for a backend node
    virtual ::grpc::Status CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::penncloud::backend::HealthCheckResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>> AsyncCheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>>(AsyncCheckNodeHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>> PrepareAsyncCheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>>(PrepareAsyncCheckNodeHealthRaw(context, request, cq));
    }
    // Receives load reports from backend nodes
    virtual ::grpc::Status ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::penncloud::backend::Acknowledgment* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>> AsyncReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>>(AsyncReportNodeLoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>> PrepareAsyncReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>>(PrepareAsyncReportNodeLoadRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Health check for a backend node
      virtual void CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Receives load reports from backend nodes
      virtual void ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>* AsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::HealthCheckResponse>* PrepareAsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>* AsyncReportNodeLoadRaw(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::penncloud::backend::Acknowledgment>* PrepareAsyncReportNodeLoadRaw(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::penncloud::backend::HealthCheckResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>> AsyncCheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>>(AsyncCheckNodeHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>> PrepareAsyncCheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>>(PrepareAsyncCheckNodeHealthRaw(context, request, cq));
    }
    ::grpc::Status ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::penncloud::backend::Acknowledgment* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>> AsyncReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>>(AsyncReportNodeLoadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>> PrepareAsyncReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>>(PrepareAsyncReportNodeLoadRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckNodeHealth(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response, std::function<void(::grpc::Status)>) override;
      void ReportNodeLoad(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>* AsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::penncloud::backend::HealthCheckResponse>* PrepareAsyncCheckNodeHealthRaw(::grpc::ClientContext* context, const ::penncloud::backend::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>* AsyncReportNodeLoadRaw(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::penncloud::backend::Acknowledgment>* PrepareAsyncReportNodeLoadRaw(::grpc::ClientContext* context, const ::penncloud::backend::LoadReport& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckNodeHealth_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportNodeLoad_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Health check for a backend node
    virtual ::grpc::Status CheckNodeHealth(::grpc::ServerContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response);
    // Receives load reports from backend nodes
    virtual ::grpc::Status ReportNodeLoad(::grpc::ServerContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckNodeHealth(::grpc::ServerContext* context, ::penncloud::backend::HealthCheckRequest* request, ::grpc::ServerAsyncResponseWriter< ::penncloud::backend::HealthCheckResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportNodeLoad(::grpc::ServerContext* context, ::penncloud::backend::LoadReport* request, ::grpc::ServerAsyncResponseWriter< ::penncloud::backend::Acknowledgment>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckNodeHealth<WithAsyncMethod_ReportNodeLoad<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::penncloud::backend::HealthCheckRequest, ::penncloud::backend::HealthCheckResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::penncloud::backend::HealthCheckRequest* request, ::penncloud::backend::HealthCheckResponse* response) { return this->CheckNodeHealth(context, request, response); }));}
    void SetMessageAllocatorFor_CheckNodeHealth(
        ::grpc::MessageAllocator< ::penncloud::backend::HealthCheckRequest, ::penncloud::backend::HealthCheckResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::penncloud::backend::HealthCheckRequest, ::penncloud::backend::HealthCheckResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckNodeHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::penncloud::backend::LoadReport, ::penncloud::backend::Acknowledgment>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::penncloud::backend::LoadReport* request, ::penncloud::backend::Acknowledgment* response) { return this->ReportNodeLoad(context, request, response); }));}
    void SetMessageAllocatorFor_ReportNodeLoad(
        ::grpc::MessageAllocator< ::penncloud::backend::LoadReport, ::penncloud::backend::Acknowledgment>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::penncloud::backend::LoadReport, ::penncloud::backend::Acknowledgment>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportNodeLoad(
      ::grpc::CallbackServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckNodeHealth<WithCallbackMethod_ReportNodeLoad<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckNodeHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportNodeLoad(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckNodeHealth(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckNodeHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportNodeLoad(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportNodeLoad(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckNodeHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckNodeHealth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::penncloud::backend::HealthCheckRequest, ::penncloud::backend::HealthCheckResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::penncloud::backend::HealthCheckRequest, ::penncloud::backend::HealthCheckResponse>* streamer) {
                       return this->StreamedCheckNodeHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckNodeHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckNodeHealth(::grpc::ServerContext* /*context*/, const ::penncloud::backend::HealthCheckRequest* /*request*/, ::penncloud::backend::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckNodeHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::penncloud::backend::HealthCheckRequest,::penncloud::backend::HealthCheckResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportNodeLoad : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportNodeLoad() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::penncloud::backend::LoadReport, ::penncloud::backend::Acknowledgment>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::penncloud::backend::LoadReport, ::penncloud::backend::Acknowledgment>* streamer) {
                       return this->StreamedReportNodeLoad(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportNodeLoad() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportNodeLoad(::grpc::ServerContext* /*context*/, const ::penncloud::backend::LoadReport* /*request*/, ::penncloud::backend::Acknowledgment* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportNodeLoad(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::penncloud::backend::LoadReport,::penncloud::backend::Acknowledgment>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckNodeHealth<WithStreamedUnaryMethod_ReportNodeLoad<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckNodeHealth<WithStreamedUnaryMethod_ReportNodeLoad<Service > > StreamedService;
};

}  // namespace backend
}  // namespace penncloud


#endif  // GRPC_backend_5fmaster_5fkv_2eproto__INCLUDED
