// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recovery.proto
// Protobuf C++ Version: 5.26.1

#include "recovery.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace recovery {

inline constexpr StartRecoveryResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::recovery::RecoveryType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StartRecoveryResponse::StartRecoveryResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StartRecoveryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StartRecoveryResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartRecoveryResponseDefaultTypeInternal() {}
  union {
    StartRecoveryResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartRecoveryResponseDefaultTypeInternal _StartRecoveryResponse_default_instance_;

inline constexpr StartRecoveryRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : log_number_{},
        _log_number_cached_byte_size_{0},
        checkpoint_version_number_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StartRecoveryRequest::StartRecoveryRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StartRecoveryRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StartRecoveryRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartRecoveryRequestDefaultTypeInternal() {}
  union {
    StartRecoveryRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartRecoveryRequestDefaultTypeInternal _StartRecoveryRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR RecoveryCompleteResponse::RecoveryCompleteResponse(::_pbi::ConstantInitialized) {}
struct RecoveryCompleteResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecoveryCompleteResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecoveryCompleteResponseDefaultTypeInternal() {}
  union {
    RecoveryCompleteResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecoveryCompleteResponseDefaultTypeInternal _RecoveryCompleteResponse_default_instance_;

inline constexpr RecoveryCompleteRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RecoveryCompleteRequest::RecoveryCompleteRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RecoveryCompleteRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecoveryCompleteRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecoveryCompleteRequestDefaultTypeInternal() {}
  union {
    RecoveryCompleteRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecoveryCompleteRequestDefaultTypeInternal _RecoveryCompleteRequest_default_instance_;

inline constexpr Log_File::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Log_File::Log_File(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct Log_FileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Log_FileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Log_FileDefaultTypeInternal() {}
  union {
    Log_File _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Log_FileDefaultTypeInternal _Log_File_default_instance_;

inline constexpr GetLogFilesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : log_number_{},
        _log_number_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetLogFilesRequest::GetLogFilesRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetLogFilesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetLogFilesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetLogFilesRequestDefaultTypeInternal() {}
  union {
    GetLogFilesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetLogFilesRequestDefaultTypeInternal _GetLogFilesRequest_default_instance_;

inline constexpr FileChunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        starting_range_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_final_chunk_{false},
        tablet_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileChunk::FileChunk(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileChunkDefaultTypeInternal() {}
  union {
    FileChunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileChunkDefaultTypeInternal _FileChunk_default_instance_;

inline constexpr CheckpointFilesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ack_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckpointFilesResponse::CheckpointFilesResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckpointFilesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckpointFilesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckpointFilesResponseDefaultTypeInternal() {}
  union {
    CheckpointFilesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckpointFilesResponseDefaultTypeInternal _CheckpointFilesResponse_default_instance_;

inline constexpr CheckpointFilesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckpointFilesRequest::CheckpointFilesRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckpointFilesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckpointFilesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckpointFilesRequestDefaultTypeInternal() {}
  union {
    CheckpointFilesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckpointFilesRequestDefaultTypeInternal _CheckpointFilesRequest_default_instance_;

inline constexpr CheckpointChunkResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : bytesreceived_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckpointChunkResponse::CheckpointChunkResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckpointChunkResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckpointChunkResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckpointChunkResponseDefaultTypeInternal() {}
  union {
    CheckpointChunkResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckpointChunkResponseDefaultTypeInternal _CheckpointChunkResponse_default_instance_;

inline constexpr LogFiles::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : log_files_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LogFiles::LogFiles(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LogFilesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogFilesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogFilesDefaultTypeInternal() {}
  union {
    LogFiles _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogFilesDefaultTypeInternal _LogFiles_default_instance_;
}  // namespace recovery
static ::_pb::Metadata file_level_metadata_recovery_2eproto[11];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_recovery_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_recovery_2eproto = nullptr;
const ::uint32_t
    TableStruct_recovery_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::StartRecoveryRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::StartRecoveryRequest, _impl_.checkpoint_version_number_),
        PROTOBUF_FIELD_OFFSET(::recovery::StartRecoveryRequest, _impl_.log_number_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::StartRecoveryResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::StartRecoveryResponse, _impl_.type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointFilesRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointFilesRequest, _impl_.address_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointFilesResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointFilesResponse, _impl_.ack_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::GetLogFilesRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::GetLogFilesRequest, _impl_.log_number_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::Log_File, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::Log_File, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::recovery::Log_File, _impl_.file_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::LogFiles, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::LogFiles, _impl_.log_files_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _impl_.is_final_chunk_),
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _impl_.tablet_id_),
        PROTOBUF_FIELD_OFFSET(::recovery::FileChunk, _impl_.starting_range_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointChunkResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::CheckpointChunkResponse, _impl_.bytesreceived_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::RecoveryCompleteRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::recovery::RecoveryCompleteRequest, _impl_.address_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::recovery::RecoveryCompleteResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::recovery::StartRecoveryRequest)},
        {10, -1, -1, sizeof(::recovery::StartRecoveryResponse)},
        {19, -1, -1, sizeof(::recovery::CheckpointFilesRequest)},
        {28, -1, -1, sizeof(::recovery::CheckpointFilesResponse)},
        {37, -1, -1, sizeof(::recovery::GetLogFilesRequest)},
        {46, -1, -1, sizeof(::recovery::Log_File)},
        {56, -1, -1, sizeof(::recovery::LogFiles)},
        {65, -1, -1, sizeof(::recovery::FileChunk)},
        {78, -1, -1, sizeof(::recovery::CheckpointChunkResponse)},
        {87, -1, -1, sizeof(::recovery::RecoveryCompleteRequest)},
        {96, -1, -1, sizeof(::recovery::RecoveryCompleteResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::recovery::_StartRecoveryRequest_default_instance_._instance,
    &::recovery::_StartRecoveryResponse_default_instance_._instance,
    &::recovery::_CheckpointFilesRequest_default_instance_._instance,
    &::recovery::_CheckpointFilesResponse_default_instance_._instance,
    &::recovery::_GetLogFilesRequest_default_instance_._instance,
    &::recovery::_Log_File_default_instance_._instance,
    &::recovery::_LogFiles_default_instance_._instance,
    &::recovery::_FileChunk_default_instance_._instance,
    &::recovery::_CheckpointChunkResponse_default_instance_._instance,
    &::recovery::_RecoveryCompleteRequest_default_instance_._instance,
    &::recovery::_RecoveryCompleteResponse_default_instance_._instance,
};
const char descriptor_table_protodef_recovery_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016recovery.proto\022\010recovery\"M\n\024StartRecov"
    "eryRequest\022!\n\031checkpoint_version_number\030"
    "\001 \001(\003\022\022\n\nlog_number\030\002 \003(\003\"=\n\025StartRecove"
    "ryResponse\022$\n\004type\030\001 \001(\0162\026.recovery.Reco"
    "veryType\")\n\026CheckpointFilesRequest\022\017\n\007ad"
    "dress\030\001 \001(\t\"&\n\027CheckpointFilesResponse\022\013"
    "\n\003ack\030\001 \001(\010\"(\n\022GetLogFilesRequest\022\022\n\nlog"
    "_number\030\001 \003(\003\".\n\010Log_File\022\017\n\007content\030\001 \001"
    "(\t\022\021\n\tfile_name\030\002 \001(\t\"1\n\010LogFiles\022%\n\tlog"
    "_files\030\001 \003(\0132\022.recovery.Log_File\"q\n\tFile"
    "Chunk\022\017\n\007content\030\001 \001(\014\022\026\n\016is_final_chunk"
    "\030\002 \001(\010\022\020\n\010filename\030\003 \001(\t\022\021\n\ttablet_id\030\004 "
    "\001(\005\022\026\n\016starting_range\030\005 \001(\t\"0\n\027Checkpoin"
    "tChunkResponse\022\025\n\rbytesReceived\030\001 \001(\005\"*\n"
    "\027RecoveryCompleteRequest\022\017\n\007address\030\001 \001("
    "\t\"\032\n\030RecoveryCompleteResponse*A\n\014Recover"
    "yType\022\014\n\010LOGFILES\020\000\022\023\n\017CHECKPOINT_FILE\020\001"
    "\022\016\n\nUP_TO_DATE\020\0022\257\003\n\017RecoveryService\022P\n\r"
    "StartRecovery\022\036.recovery.StartRecoveryRe"
    "quest\032\037.recovery.StartRecoveryResponse\022\?"
    "\n\013GetLogFiles\022\034.recovery.GetLogFilesRequ"
    "est\032\022.recovery.LogFiles\022Y\n\022GetCheckpoint"
    "Files\022 .recovery.CheckpointFilesRequest\032"
    "!.recovery.CheckpointFilesResponse\022M\n\023Se"
    "ndCheckpointChunk\022\023.recovery.FileChunk\032!"
    ".recovery.CheckpointChunkResponse\022_\n\026Not"
    "ifyRecoveryComplete\022!.recovery.RecoveryC"
    "ompleteRequest\032\".recovery.RecoveryComple"
    "teResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_recovery_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_recovery_2eproto = {
    false,
    false,
    1138,
    descriptor_table_protodef_recovery_2eproto,
    "recovery.proto",
    &descriptor_table_recovery_2eproto_once,
    nullptr,
    0,
    11,
    schemas,
    file_default_instances,
    TableStruct_recovery_2eproto::offsets,
    file_level_metadata_recovery_2eproto,
    file_level_enum_descriptors_recovery_2eproto,
    file_level_service_descriptors_recovery_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_recovery_2eproto_getter() {
  return &descriptor_table_recovery_2eproto;
}
namespace recovery {
const ::google::protobuf::EnumDescriptor* RecoveryType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_recovery_2eproto);
  return file_level_enum_descriptors_recovery_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RecoveryType_internal_data_[] = {
    196608u, 0u, };
bool RecoveryType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class StartRecoveryRequest::_Internal {
 public:
};

StartRecoveryRequest::StartRecoveryRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.StartRecoveryRequest)
}
inline PROTOBUF_NDEBUG_INLINE StartRecoveryRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : log_number_{visibility, arena, from.log_number_},
        _log_number_cached_byte_size_{0},
        _cached_size_{0} {}

StartRecoveryRequest::StartRecoveryRequest(
    ::google::protobuf::Arena* arena,
    const StartRecoveryRequest& from)
    : ::google::protobuf::Message(arena) {
  StartRecoveryRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.checkpoint_version_number_ = from._impl_.checkpoint_version_number_;

  // @@protoc_insertion_point(copy_constructor:recovery.StartRecoveryRequest)
}
inline PROTOBUF_NDEBUG_INLINE StartRecoveryRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : log_number_{visibility, arena},
        _log_number_cached_byte_size_{0},
        _cached_size_{0} {}

inline void StartRecoveryRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.checkpoint_version_number_ = {};
}
StartRecoveryRequest::~StartRecoveryRequest() {
  // @@protoc_insertion_point(destructor:recovery.StartRecoveryRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StartRecoveryRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
StartRecoveryRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(StartRecoveryRequest, _impl_._cached_size_),
              false,
          },
          &StartRecoveryRequest::MergeImpl,
          &StartRecoveryRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void StartRecoveryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.StartRecoveryRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.log_number_.Clear();
  _impl_.checkpoint_version_number_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StartRecoveryRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> StartRecoveryRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StartRecoveryRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::StartRecoveryRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int64 log_number = 2;
    {::_pbi::TcParser::FastV64P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(StartRecoveryRequest, _impl_.log_number_)}},
    // int64 checkpoint_version_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(StartRecoveryRequest, _impl_.checkpoint_version_number_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StartRecoveryRequest, _impl_.checkpoint_version_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 checkpoint_version_number = 1;
    {PROTOBUF_FIELD_OFFSET(StartRecoveryRequest, _impl_.checkpoint_version_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // repeated int64 log_number = 2;
    {PROTOBUF_FIELD_OFFSET(StartRecoveryRequest, _impl_.log_number_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* StartRecoveryRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.StartRecoveryRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 checkpoint_version_number = 1;
  if (this->_internal_checkpoint_version_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_checkpoint_version_number(), target);
  }

  // repeated int64 log_number = 2;
  {
    int byte_size = _impl_._log_number_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          2, _internal_log_number(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.StartRecoveryRequest)
  return target;
}

::size_t StartRecoveryRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.StartRecoveryRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 log_number = 2;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_log_number())
    ;
    _impl_._log_number_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // int64 checkpoint_version_number = 1;
  if (this->_internal_checkpoint_version_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_checkpoint_version_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void StartRecoveryRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StartRecoveryRequest*>(&to_msg);
  auto& from = static_cast<const StartRecoveryRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.StartRecoveryRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_log_number()->MergeFrom(from._internal_log_number());
  if (from._internal_checkpoint_version_number() != 0) {
    _this->_impl_.checkpoint_version_number_ = from._impl_.checkpoint_version_number_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StartRecoveryRequest::CopyFrom(const StartRecoveryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.StartRecoveryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StartRecoveryRequest::IsInitialized() const {
  return true;
}

void StartRecoveryRequest::InternalSwap(StartRecoveryRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.log_number_.InternalSwap(&other->_impl_.log_number_);
        swap(_impl_.checkpoint_version_number_, other->_impl_.checkpoint_version_number_);
}

::google::protobuf::Metadata StartRecoveryRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[0]);
}
// ===================================================================

class StartRecoveryResponse::_Internal {
 public:
};

StartRecoveryResponse::StartRecoveryResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.StartRecoveryResponse)
}
StartRecoveryResponse::StartRecoveryResponse(
    ::google::protobuf::Arena* arena, const StartRecoveryResponse& from)
    : StartRecoveryResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE StartRecoveryResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void StartRecoveryResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
StartRecoveryResponse::~StartRecoveryResponse() {
  // @@protoc_insertion_point(destructor:recovery.StartRecoveryResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StartRecoveryResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
StartRecoveryResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(StartRecoveryResponse, _impl_._cached_size_),
              false,
          },
          &StartRecoveryResponse::MergeImpl,
          &StartRecoveryResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void StartRecoveryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.StartRecoveryResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* StartRecoveryResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> StartRecoveryResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_StartRecoveryResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::StartRecoveryResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .recovery.RecoveryType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StartRecoveryResponse, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StartRecoveryResponse, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .recovery.RecoveryType type = 1;
    {PROTOBUF_FIELD_OFFSET(StartRecoveryResponse, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* StartRecoveryResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.StartRecoveryResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .recovery.RecoveryType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.StartRecoveryResponse)
  return target;
}

::size_t StartRecoveryResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.StartRecoveryResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .recovery.RecoveryType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void StartRecoveryResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StartRecoveryResponse*>(&to_msg);
  auto& from = static_cast<const StartRecoveryResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.StartRecoveryResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StartRecoveryResponse::CopyFrom(const StartRecoveryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.StartRecoveryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool StartRecoveryResponse::IsInitialized() const {
  return true;
}

void StartRecoveryResponse::InternalSwap(StartRecoveryResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata StartRecoveryResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[1]);
}
// ===================================================================

class CheckpointFilesRequest::_Internal {
 public:
};

CheckpointFilesRequest::CheckpointFilesRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.CheckpointFilesRequest)
}
inline PROTOBUF_NDEBUG_INLINE CheckpointFilesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        _cached_size_{0} {}

CheckpointFilesRequest::CheckpointFilesRequest(
    ::google::protobuf::Arena* arena,
    const CheckpointFilesRequest& from)
    : ::google::protobuf::Message(arena) {
  CheckpointFilesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recovery.CheckpointFilesRequest)
}
inline PROTOBUF_NDEBUG_INLINE CheckpointFilesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        _cached_size_{0} {}

inline void CheckpointFilesRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CheckpointFilesRequest::~CheckpointFilesRequest() {
  // @@protoc_insertion_point(destructor:recovery.CheckpointFilesRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckpointFilesRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CheckpointFilesRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(CheckpointFilesRequest, _impl_._cached_size_),
              false,
          },
          &CheckpointFilesRequest::MergeImpl,
          &CheckpointFilesRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CheckpointFilesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.CheckpointFilesRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckpointFilesRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 47, 2> CheckpointFilesRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckpointFilesRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::CheckpointFilesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string address = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CheckpointFilesRequest, _impl_.address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string address = 1;
    {PROTOBUF_FIELD_OFFSET(CheckpointFilesRequest, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\7\0\0\0\0\0\0"
    "recovery.CheckpointFilesRequest"
    "address"
  }},
};

::uint8_t* CheckpointFilesRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.CheckpointFilesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.CheckpointFilesRequest.address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.CheckpointFilesRequest)
  return target;
}

::size_t CheckpointFilesRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.CheckpointFilesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CheckpointFilesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckpointFilesRequest*>(&to_msg);
  auto& from = static_cast<const CheckpointFilesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.CheckpointFilesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckpointFilesRequest::CopyFrom(const CheckpointFilesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.CheckpointFilesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckpointFilesRequest::IsInitialized() const {
  return true;
}

void CheckpointFilesRequest::InternalSwap(CheckpointFilesRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
}

::google::protobuf::Metadata CheckpointFilesRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[2]);
}
// ===================================================================

class CheckpointFilesResponse::_Internal {
 public:
};

CheckpointFilesResponse::CheckpointFilesResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.CheckpointFilesResponse)
}
CheckpointFilesResponse::CheckpointFilesResponse(
    ::google::protobuf::Arena* arena, const CheckpointFilesResponse& from)
    : CheckpointFilesResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CheckpointFilesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CheckpointFilesResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ack_ = {};
}
CheckpointFilesResponse::~CheckpointFilesResponse() {
  // @@protoc_insertion_point(destructor:recovery.CheckpointFilesResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckpointFilesResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CheckpointFilesResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(CheckpointFilesResponse, _impl_._cached_size_),
              false,
          },
          &CheckpointFilesResponse::MergeImpl,
          &CheckpointFilesResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CheckpointFilesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.CheckpointFilesResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ack_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckpointFilesResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CheckpointFilesResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckpointFilesResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::CheckpointFilesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool ack = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CheckpointFilesResponse, _impl_.ack_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckpointFilesResponse, _impl_.ack_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ack = 1;
    {PROTOBUF_FIELD_OFFSET(CheckpointFilesResponse, _impl_.ack_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CheckpointFilesResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.CheckpointFilesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool ack = 1;
  if (this->_internal_ack() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_ack(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.CheckpointFilesResponse)
  return target;
}

::size_t CheckpointFilesResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.CheckpointFilesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ack = 1;
  if (this->_internal_ack() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CheckpointFilesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckpointFilesResponse*>(&to_msg);
  auto& from = static_cast<const CheckpointFilesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.CheckpointFilesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ack() != 0) {
    _this->_impl_.ack_ = from._impl_.ack_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckpointFilesResponse::CopyFrom(const CheckpointFilesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.CheckpointFilesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckpointFilesResponse::IsInitialized() const {
  return true;
}

void CheckpointFilesResponse::InternalSwap(CheckpointFilesResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.ack_, other->_impl_.ack_);
}

::google::protobuf::Metadata CheckpointFilesResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[3]);
}
// ===================================================================

class GetLogFilesRequest::_Internal {
 public:
};

GetLogFilesRequest::GetLogFilesRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.GetLogFilesRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetLogFilesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : log_number_{visibility, arena, from.log_number_},
        _log_number_cached_byte_size_{0},
        _cached_size_{0} {}

GetLogFilesRequest::GetLogFilesRequest(
    ::google::protobuf::Arena* arena,
    const GetLogFilesRequest& from)
    : ::google::protobuf::Message(arena) {
  GetLogFilesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recovery.GetLogFilesRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetLogFilesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : log_number_{visibility, arena},
        _log_number_cached_byte_size_{0},
        _cached_size_{0} {}

inline void GetLogFilesRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetLogFilesRequest::~GetLogFilesRequest() {
  // @@protoc_insertion_point(destructor:recovery.GetLogFilesRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetLogFilesRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetLogFilesRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(GetLogFilesRequest, _impl_._cached_size_),
              false,
          },
          &GetLogFilesRequest::MergeImpl,
          &GetLogFilesRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void GetLogFilesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.GetLogFilesRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.log_number_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GetLogFilesRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetLogFilesRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetLogFilesRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::GetLogFilesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated int64 log_number = 1;
    {::_pbi::TcParser::FastV64P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetLogFilesRequest, _impl_.log_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated int64 log_number = 1;
    {PROTOBUF_FIELD_OFFSET(GetLogFilesRequest, _impl_.log_number_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* GetLogFilesRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.GetLogFilesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated int64 log_number = 1;
  {
    int byte_size = _impl_._log_number_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          1, _internal_log_number(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.GetLogFilesRequest)
  return target;
}

::size_t GetLogFilesRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.GetLogFilesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 log_number = 1;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int64Size(
        this->_internal_log_number())
    ;
    _impl_._log_number_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetLogFilesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetLogFilesRequest*>(&to_msg);
  auto& from = static_cast<const GetLogFilesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.GetLogFilesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_log_number()->MergeFrom(from._internal_log_number());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetLogFilesRequest::CopyFrom(const GetLogFilesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.GetLogFilesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GetLogFilesRequest::IsInitialized() const {
  return true;
}

void GetLogFilesRequest::InternalSwap(GetLogFilesRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.log_number_.InternalSwap(&other->_impl_.log_number_);
}

::google::protobuf::Metadata GetLogFilesRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[4]);
}
// ===================================================================

class Log_File::_Internal {
 public:
};

Log_File::Log_File(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.Log_File)
}
inline PROTOBUF_NDEBUG_INLINE Log_File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : content_(arena, from.content_),
        file_name_(arena, from.file_name_),
        _cached_size_{0} {}

Log_File::Log_File(
    ::google::protobuf::Arena* arena,
    const Log_File& from)
    : ::google::protobuf::Message(arena) {
  Log_File* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recovery.Log_File)
}
inline PROTOBUF_NDEBUG_INLINE Log_File::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        file_name_(arena),
        _cached_size_{0} {}

inline void Log_File::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Log_File::~Log_File() {
  // @@protoc_insertion_point(destructor:recovery.Log_File)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Log_File::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.content_.Destroy();
  _impl_.file_name_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Log_File::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Log_File, _impl_._cached_size_),
              false,
          },
          &Log_File::MergeImpl,
          &Log_File::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Log_File::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.Log_File)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.file_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Log_File::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> Log_File::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Log_File_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::Log_File>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string file_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Log_File, _impl_.file_name_)}},
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Log_File, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(Log_File, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string file_name = 2;
    {PROTOBUF_FIELD_OFFSET(Log_File, _impl_.file_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\7\11\0\0\0\0\0"
    "recovery.Log_File"
    "content"
    "file_name"
  }},
};

::uint8_t* Log_File::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.Log_File)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string content = 1;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.Log_File.content");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    const std::string& _s = this->_internal_file_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.Log_File.file_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.Log_File)
  return target;
}

::size_t Log_File::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.Log_File)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string content = 1;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_content());
  }

  // string file_name = 2;
  if (!this->_internal_file_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Log_File::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Log_File*>(&to_msg);
  auto& from = static_cast<const Log_File&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.Log_File)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (!from._internal_file_name().empty()) {
    _this->_internal_set_file_name(from._internal_file_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Log_File::CopyFrom(const Log_File& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.Log_File)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Log_File::IsInitialized() const {
  return true;
}

void Log_File::InternalSwap(Log_File* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
}

::google::protobuf::Metadata Log_File::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[5]);
}
// ===================================================================

class LogFiles::_Internal {
 public:
};

LogFiles::LogFiles(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.LogFiles)
}
inline PROTOBUF_NDEBUG_INLINE LogFiles::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : log_files_{visibility, arena, from.log_files_},
        _cached_size_{0} {}

LogFiles::LogFiles(
    ::google::protobuf::Arena* arena,
    const LogFiles& from)
    : ::google::protobuf::Message(arena) {
  LogFiles* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recovery.LogFiles)
}
inline PROTOBUF_NDEBUG_INLINE LogFiles::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : log_files_{visibility, arena},
        _cached_size_{0} {}

inline void LogFiles::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LogFiles::~LogFiles() {
  // @@protoc_insertion_point(destructor:recovery.LogFiles)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LogFiles::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LogFiles::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LogFiles, _impl_._cached_size_),
              false,
          },
          &LogFiles::MergeImpl,
          &LogFiles::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LogFiles::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.LogFiles)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.log_files_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LogFiles::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> LogFiles::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_LogFiles_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::LogFiles>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .recovery.Log_File log_files = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LogFiles, _impl_.log_files_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .recovery.Log_File log_files = 1;
    {PROTOBUF_FIELD_OFFSET(LogFiles, _impl_.log_files_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::recovery::Log_File>()},
  }}, {{
  }},
};

::uint8_t* LogFiles::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.LogFiles)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .recovery.Log_File log_files = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_log_files_size());
       i < n; i++) {
    const auto& repfield = this->_internal_log_files().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.LogFiles)
  return target;
}

::size_t LogFiles::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.LogFiles)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .recovery.Log_File log_files = 1;
  total_size += 1UL * this->_internal_log_files_size();
  for (const auto& msg : this->_internal_log_files()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LogFiles::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LogFiles*>(&to_msg);
  auto& from = static_cast<const LogFiles&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.LogFiles)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_log_files()->MergeFrom(
      from._internal_log_files());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LogFiles::CopyFrom(const LogFiles& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.LogFiles)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LogFiles::IsInitialized() const {
  return true;
}

void LogFiles::InternalSwap(LogFiles* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.log_files_.InternalSwap(&other->_impl_.log_files_);
}

::google::protobuf::Metadata LogFiles::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[6]);
}
// ===================================================================

class FileChunk::_Internal {
 public:
};

FileChunk::FileChunk(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.FileChunk)
}
inline PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : content_(arena, from.content_),
        filename_(arena, from.filename_),
        starting_range_(arena, from.starting_range_),
        _cached_size_{0} {}

FileChunk::FileChunk(
    ::google::protobuf::Arena* arena,
    const FileChunk& from)
    : ::google::protobuf::Message(arena) {
  FileChunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_final_chunk_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, is_final_chunk_),
           offsetof(Impl_, tablet_id_) -
               offsetof(Impl_, is_final_chunk_) +
               sizeof(Impl_::tablet_id_));

  // @@protoc_insertion_point(copy_constructor:recovery.FileChunk)
}
inline PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        filename_(arena),
        starting_range_(arena),
        _cached_size_{0} {}

inline void FileChunk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_final_chunk_),
           0,
           offsetof(Impl_, tablet_id_) -
               offsetof(Impl_, is_final_chunk_) +
               sizeof(Impl_::tablet_id_));
}
FileChunk::~FileChunk() {
  // @@protoc_insertion_point(destructor:recovery.FileChunk)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileChunk::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.content_.Destroy();
  _impl_.filename_.Destroy();
  _impl_.starting_range_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FileChunk::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._cached_size_),
              false,
          },
          &FileChunk::MergeImpl,
          &FileChunk::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void FileChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.FileChunk)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.filename_.ClearToEmpty();
  _impl_.starting_range_.ClearToEmpty();
  ::memset(&_impl_.is_final_chunk_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.tablet_id_) -
      reinterpret_cast<char*>(&_impl_.is_final_chunk_)) + sizeof(_impl_.tablet_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileChunk::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 49, 2> FileChunk::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileChunk_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::FileChunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes content = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.content_)}},
    // bool is_final_chunk = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileChunk, _impl_.is_final_chunk_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.is_final_chunk_)}},
    // string filename = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filename_)}},
    // int32 tablet_id = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileChunk, _impl_.tablet_id_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.tablet_id_)}},
    // string starting_range = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.starting_range_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes content = 1;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool is_final_chunk = 2;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.is_final_chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string filename = 3;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 tablet_id = 4;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.tablet_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string starting_range = 5;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.starting_range_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\0\10\0\16\0\0"
    "recovery.FileChunk"
    "filename"
    "starting_range"
  }},
};

::uint8_t* FileChunk::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.FileChunk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes content = 1;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // bool is_final_chunk = 2;
  if (this->_internal_is_final_chunk() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_is_final_chunk(), target);
  }

  // string filename = 3;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.FileChunk.filename");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 tablet_id = 4;
  if (this->_internal_tablet_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_tablet_id(), target);
  }

  // string starting_range = 5;
  if (!this->_internal_starting_range().empty()) {
    const std::string& _s = this->_internal_starting_range();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.FileChunk.starting_range");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.FileChunk)
  return target;
}

::size_t FileChunk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.FileChunk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes content = 1;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_content());
  }

  // string filename = 3;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // string starting_range = 5;
  if (!this->_internal_starting_range().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_starting_range());
  }

  // bool is_final_chunk = 2;
  if (this->_internal_is_final_chunk() != 0) {
    total_size += 2;
  }

  // int32 tablet_id = 4;
  if (this->_internal_tablet_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_tablet_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void FileChunk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileChunk*>(&to_msg);
  auto& from = static_cast<const FileChunk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.FileChunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_starting_range().empty()) {
    _this->_internal_set_starting_range(from._internal_starting_range());
  }
  if (from._internal_is_final_chunk() != 0) {
    _this->_impl_.is_final_chunk_ = from._impl_.is_final_chunk_;
  }
  if (from._internal_tablet_id() != 0) {
    _this->_impl_.tablet_id_ = from._impl_.tablet_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileChunk::CopyFrom(const FileChunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.FileChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileChunk::IsInitialized() const {
  return true;
}

void FileChunk::InternalSwap(FileChunk* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.starting_range_, &other->_impl_.starting_range_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.tablet_id_)
      + sizeof(FileChunk::_impl_.tablet_id_)
      - PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.is_final_chunk_)>(
          reinterpret_cast<char*>(&_impl_.is_final_chunk_),
          reinterpret_cast<char*>(&other->_impl_.is_final_chunk_));
}

::google::protobuf::Metadata FileChunk::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[7]);
}
// ===================================================================

class CheckpointChunkResponse::_Internal {
 public:
};

CheckpointChunkResponse::CheckpointChunkResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.CheckpointChunkResponse)
}
CheckpointChunkResponse::CheckpointChunkResponse(
    ::google::protobuf::Arena* arena, const CheckpointChunkResponse& from)
    : CheckpointChunkResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CheckpointChunkResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CheckpointChunkResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.bytesreceived_ = {};
}
CheckpointChunkResponse::~CheckpointChunkResponse() {
  // @@protoc_insertion_point(destructor:recovery.CheckpointChunkResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckpointChunkResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CheckpointChunkResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(CheckpointChunkResponse, _impl_._cached_size_),
              false,
          },
          &CheckpointChunkResponse::MergeImpl,
          &CheckpointChunkResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void CheckpointChunkResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.CheckpointChunkResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bytesreceived_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CheckpointChunkResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CheckpointChunkResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckpointChunkResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::CheckpointChunkResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 bytesReceived = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CheckpointChunkResponse, _impl_.bytesreceived_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckpointChunkResponse, _impl_.bytesreceived_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 bytesReceived = 1;
    {PROTOBUF_FIELD_OFFSET(CheckpointChunkResponse, _impl_.bytesreceived_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CheckpointChunkResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.CheckpointChunkResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 bytesReceived = 1;
  if (this->_internal_bytesreceived() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_bytesreceived(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.CheckpointChunkResponse)
  return target;
}

::size_t CheckpointChunkResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.CheckpointChunkResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 bytesReceived = 1;
  if (this->_internal_bytesreceived() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_bytesreceived());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CheckpointChunkResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckpointChunkResponse*>(&to_msg);
  auto& from = static_cast<const CheckpointChunkResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.CheckpointChunkResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_bytesreceived() != 0) {
    _this->_impl_.bytesreceived_ = from._impl_.bytesreceived_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckpointChunkResponse::CopyFrom(const CheckpointChunkResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.CheckpointChunkResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CheckpointChunkResponse::IsInitialized() const {
  return true;
}

void CheckpointChunkResponse::InternalSwap(CheckpointChunkResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.bytesreceived_, other->_impl_.bytesreceived_);
}

::google::protobuf::Metadata CheckpointChunkResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[8]);
}
// ===================================================================

class RecoveryCompleteRequest::_Internal {
 public:
};

RecoveryCompleteRequest::RecoveryCompleteRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:recovery.RecoveryCompleteRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecoveryCompleteRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        _cached_size_{0} {}

RecoveryCompleteRequest::RecoveryCompleteRequest(
    ::google::protobuf::Arena* arena,
    const RecoveryCompleteRequest& from)
    : ::google::protobuf::Message(arena) {
  RecoveryCompleteRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:recovery.RecoveryCompleteRequest)
}
inline PROTOBUF_NDEBUG_INLINE RecoveryCompleteRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        _cached_size_{0} {}

inline void RecoveryCompleteRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RecoveryCompleteRequest::~RecoveryCompleteRequest() {
  // @@protoc_insertion_point(destructor:recovery.RecoveryCompleteRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RecoveryCompleteRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RecoveryCompleteRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(RecoveryCompleteRequest, _impl_._cached_size_),
              false,
          },
          &RecoveryCompleteRequest::MergeImpl,
          &RecoveryCompleteRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void RecoveryCompleteRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:recovery.RecoveryCompleteRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RecoveryCompleteRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 48, 2> RecoveryCompleteRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RecoveryCompleteRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::recovery::RecoveryCompleteRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string address = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RecoveryCompleteRequest, _impl_.address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string address = 1;
    {PROTOBUF_FIELD_OFFSET(RecoveryCompleteRequest, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\7\0\0\0\0\0\0"
    "recovery.RecoveryCompleteRequest"
    "address"
  }},
};

::uint8_t* RecoveryCompleteRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:recovery.RecoveryCompleteRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "recovery.RecoveryCompleteRequest.address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:recovery.RecoveryCompleteRequest)
  return target;
}

::size_t RecoveryCompleteRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:recovery.RecoveryCompleteRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RecoveryCompleteRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RecoveryCompleteRequest*>(&to_msg);
  auto& from = static_cast<const RecoveryCompleteRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:recovery.RecoveryCompleteRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RecoveryCompleteRequest::CopyFrom(const RecoveryCompleteRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:recovery.RecoveryCompleteRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RecoveryCompleteRequest::IsInitialized() const {
  return true;
}

void RecoveryCompleteRequest::InternalSwap(RecoveryCompleteRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
}

::google::protobuf::Metadata RecoveryCompleteRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[9]);
}
// ===================================================================

class RecoveryCompleteResponse::_Internal {
 public:
};

RecoveryCompleteResponse::RecoveryCompleteResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:recovery.RecoveryCompleteResponse)
}
RecoveryCompleteResponse::RecoveryCompleteResponse(
    ::google::protobuf::Arena* arena,
    const RecoveryCompleteResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  RecoveryCompleteResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:recovery.RecoveryCompleteResponse)
}









::google::protobuf::Metadata RecoveryCompleteResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_recovery_2eproto_getter,
                                   &descriptor_table_recovery_2eproto_once,
                                   file_level_metadata_recovery_2eproto[10]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace recovery
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_recovery_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
